[package]
name = "letter_combinations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
progress_bar = { path = "../progress_bar" }
console_utils = { path = "../console_utils" }
rayon = "1.10"
